edition = "2021"
color = "Always"
max_width = 120
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
format_macro_matchers = true
fn_single_line = true
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
#report_todo = "Always"
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
