[package]
name = "konrad_err"
version = "0.1.0"
authors = ["Simon Kunz <simon.kunz21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
konrad_span = {path = "../konrad_span"}
typed-builder = "0.9.0"
